# copy from k8-resource --> volume --> 02-ebs-static-pvc.yaml --> pod. Do some changes 
apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
  labels:
    purpose: "anti-affinity-demo"
spec:
  # search as kubernetes--> click on kubernetes--> search as affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: NotIn #anti-affinity
            values:
            - gpu
  containers:
  - name: nginx
    image: nginx
  #seach in google as k8-taint and taloeration --> click on kubernetes 
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"